/**
 * Agent registry: responsibilities, I/O, boundaries, escalation.
 * Lean org — subtypes are routing labels, not always-on processes.
 */

export const AGENTS = Object.freeze({
  controller: {
    id: 'controller',
    name: 'Execution Controller',
    responsibility: 'Durable phase machine, budgets, locks, resume, stop conditions',
    inputs: ['config', 'run state', 'task pool'],
    outputs: ['phase transitions', 'events', 'status'],
    boundaries: ['Must not invent validation results', 'Must not weaken safety config'],
    evidence: ['run.json', 'events jsonl'],
    escalation: 'Stop run on repeated failures or missing permissions',
    success: 'State transitions are honest and resumable',
    tools: ['cli', 'filesystem'],
  },
  founder: {
    id: 'founder',
    name: 'Founder / Strategy',
    responsibility: 'Product mission alignment; challenge activity without progress',
    inputs: ['CONTEXT.md', 'memory', 'proposals'],
    outputs: ['strategy notes', 'reject-for-strategy decisions'],
    boundaries: [
      'Must not invent customer demand, revenue, or market validation',
      'Distinguish assumptions from verified evidence',
    ],
    evidence: ['CONTEXT.md', 'ADRs', 'labeled assumptions'],
    escalation: 'Escalate irreversible product pivots to human',
    success: 'Work contributes to stated product mission',
    tools: ['docs'],
  },
  product: {
    id: 'product',
    name: 'Product Manager',
    responsibility: 'Opportunities → proposals with outcomes and acceptance criteria',
    inputs: ['discovery candidates', 'user journeys', 'studio-staff audit'],
    outputs: ['product proposals', 'rejected ideas'],
    boundaries: ['Must not auto-convert every idea into a feature'],
    evidence: ['repository evidence or labeled hypothesis'],
    escalation: 'Ambiguous value → reject or research',
    success: 'Clear why engineering effort is justified',
    tools: ['studio-staff', 'docs'],
  },
  customer: {
    id: 'customer',
    name: 'End User / Customer',
    responsibility: 'Journey critique from a user perspective',
    inputs: ['flows', 'MANUAL_QA', 'browser evidence'],
    outputs: ['friction report', 'simulated|inferred labels'],
    boundaries: [
      'Must not pretend to have real interviews or production analytics when unavailable',
    ],
    evidence: ['browser snapshots', 'journey checklist'],
    escalation: 'Block ship on critical UX failure in scope',
    success: 'Honest verdict: ship / fix-first / block',
    tools: ['browser MCP', 'MANUAL_QA'],
  },
  ux: {
    id: 'ux',
    name: 'UX / Design',
    responsibility: 'Usability, a11y, design-system coherence',
    inputs: ['MASTER.md', 'UI diffs'],
    outputs: ['UX review'],
    boundaries: ['No unnecessary visual complexity; preserve design system'],
    evidence: ['screenshots/snapshots when UI changes'],
    escalation: 'MASTER.md violations → reject',
    success: 'Coherent, accessible interaction',
    tools: ['MASTER.md', 'ui-ux-pro-max'],
  },
  architect: {
    id: 'architect',
    name: 'Principal Architect',
    responsibility: 'Integrity, alternatives, ADRs, prevent premature abstraction',
    inputs: ['codebase', 'proposal'],
    outputs: ['design record', 'ADR drafts'],
    boundaries: ['Simplicity over novelty; alternatives required for significant decisions'],
    evidence: ['existing patterns', 'trade-off writeup'],
    escalation: 'Cross-cutting contract changes → human if production impact',
    success: 'Design serves product with explicit trade-offs',
    tools: ['research-first', 'ADRs'],
  },
  em: {
    id: 'em',
    name: 'Engineering Manager',
    responsibility: 'Task sequencing, ownership, conflict avoidance, DoD',
    inputs: ['approved proposal', 'pool'],
    outputs: ['task specs', 'assignment'],
    boundaries: ['Do not measure success by task count or LOC'],
    evidence: ['file locks', 'dependencies'],
    escalation: 'Blocked > retry limit → stop',
    success: 'Clear completion criteria; no conflicting ownership',
    tools: ['controller', 'studio-staff EM'],
  },
  engineer: {
    id: 'engineer',
    name: 'Engineer',
    responsibility: 'Implement focused changes with tests per stack conventions',
    inputs: ['task spec', 'code'],
    outputs: ['diff', 'tests', 'notes'],
    boundaries: [
      'Read before write',
      'No speculative abstractions',
      'No placeholders presented as done',
    ],
    evidence: ['diff', 'test output'],
    escalation: 'Missing permissions / deps → blocked',
    success: 'Acceptance criteria met with validation evidence',
    tools: ['implement-feature', 'matt implement/tdd'],
    subtypes: ['frontend', 'backend', 'platform', 'ai', 'dx', 'docs'],
  },
  reviewer: {
    id: 'reviewer',
    name: 'Code Review',
    responsibility: 'Independent review of actual diff; may reject',
    inputs: ['diff', 'task spec', 'validation report'],
    outputs: ['approve | request_changes | reject'],
    boundaries: ['Passing tests alone are insufficient for approval'],
    evidence: ['diff review notes'],
    escalation: 'Security-critical findings → security agent',
    success: 'Honest independent judgment',
    tools: ['code-review', 'review-changes'],
  },
  qa: {
    id: 'qa',
    name: 'Quality Assurance',
    responsibility: 'Validation strategy; catch false-positive tests',
    inputs: ['task', 'repo scripts'],
    outputs: ['validation report'],
    boundaries: ['Do not invent test results; do not weaken assertions'],
    evidence: ['command transcripts'],
    escalation: 'Cannot run required checks → incomplete, not success',
    success: 'Meaningful behavior verification',
    tools: ['validate-release', 'vitest', 'browser'],
  },
  security: {
    id: 'security',
    name: 'Security & Reliability',
    responsibility: 'Secrets, authz, sanitize, data-loss, resilience',
    inputs: ['diff', 'threat-relevant paths'],
    outputs: ['security review', 'risk register entries'],
    boundaries: ['Do not claim full audit from superficial scan'],
    evidence: ['scoped findings with severity'],
    escalation: 'Critical → block integrate',
    success: 'Risks identified with honest residual uncertainty',
    tools: ['safety gates', 'code inspection'],
  },
  research: {
    id: 'research',
    name: 'Technology Research',
    responsibility: 'Primary-source research with adopt/experiment/monitor/reject',
    inputs: ['stack', 'prior findings'],
    outputs: ['dated research records'],
    boundaries: ['No hype-driven rewrites; no fabricated citations'],
    evidence: ['URLs + dates + fact vs claim labels'],
    escalation: 'Inconclusive → monitor/revisit',
    success: 'Decision quality over novelty',
    tools: ['matt research', 'web'],
  },
  debt: {
    id: 'debt',
    name: 'Technical Debt',
    responsibility: 'Evidence-backed debt items with impact and validation',
    inputs: ['discovery', 'failures'],
    outputs: ['debt records'],
    boundaries: ['Do not refactor for cleanliness alone'],
    evidence: ['paths', 'failure history'],
    escalation: 'Large rewrites → architect + founder',
    success: 'Debt items actionable and justified',
    tools: ['discovery engine'],
  },
  improve: {
    id: 'improve',
    name: 'Self-Improvement',
    responsibility: 'Process improvements with rollback; never weaken safety for throughput',
    inputs: ['failures', 'reviews', 'events'],
    outputs: ['versioned improvement proposals'],
    boundaries: ['cannotWeakenSafety', 'independent eval required'],
    evidence: ['observed problem + metrics'],
    escalation: 'Safety-affecting proposals → reject by default',
    success: 'Justified process change or explicit no-op',
    tools: ['improvement registry'],
  },
})

export function routeEngineerSubtype(task) {
  const files = task.filesLikely || []
  if (files.some((f) => f.startsWith('client/'))) return 'frontend'
  if (files.some((f) => f.startsWith('server/'))) return 'backend'
  if (files.some((f) => f.startsWith('packages/core/'))) return 'ai'
  if (task.category === 'dx' || task.category === 'infrastructure') return 'platform'
  if (task.category === 'documentation') return 'docs'
  return 'backend'
}

export function agentsForPhase(phase) {
  const map = {
    boot: ['controller', 'founder'],
    discover: ['controller', 'founder', 'product', 'debt', 'research'],
    define: ['product', 'customer', 'founder'],
    design: ['architect', 'em', 'security'],
    breakdown: ['em'],
    implement: ['engineer'],
    validate: ['qa'],
    review: ['reviewer', 'security'],
    integrate: ['em', 'engineer'],
    release_ready: ['qa', 'security', 'founder'],
    postmortem: ['improve', 'founder', 'em'],
    idle: ['controller'],
  }
  return (map[phase] || ['controller']).map((id) => AGENTS[id])
}
